name: Docker Image CI

on:
  release:
    types:
      - published

jobs:

  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            weygu/nebulagraph-gephi-exchange
          tags: |
            # git tag & latest coverred
            type=ref,event=tag
            # git branch
            type=ref,event=branch
            # v3.0.0
            type=semver,pattern=v{{version}}
            # v3
            type=semver,pattern=v{{major}}
            # v3.0
            type=semver,pattern=v{{major}}.{{minor}}
      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
